CREATE TABLE `employers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employerType` enum('individual','company','partnership') NOT NULL,
	`companyName` varchar(500) NOT NULL,
	`taxId` varchar(20) NOT NULL,
	`registrationNumber` varchar(50),
	`contactPerson` varchar(255),
	`contactPosition` varchar(255),
	`phone` varchar(20),
	`email` varchar(320),
	`fax` varchar(20),
	`address` text,
	`subdistrict` varchar(100),
	`district` varchar(100),
	`province` varchar(100),
	`postalCode` varchar(10),
	`businessType` varchar(255),
	`numberOfEmployees` int,
	`capitalAmount` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `employers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`titleTh` varchar(50),
	`firstNameTh` varchar(255) NOT NULL,
	`lastNameTh` varchar(255) NOT NULL,
	`titleEn` varchar(50),
	`firstNameEn` varchar(255),
	`lastNameEn` varchar(255),
	`nationality` varchar(100) NOT NULL,
	`dateOfBirth` date,
	`gender` enum('male','female'),
	`passportNo` varchar(50) NOT NULL,
	`passportIssueDate` date,
	`passportExpiryDate` date,
	`visaType` varchar(50),
	`visaNo` varchar(50),
	`visaExpiryDate` date,
	`workPermitNo` varchar(50),
	`workPermitExpiryDate` date,
	`addressTh` text,
	`subdistrictTh` varchar(100),
	`districtTh` varchar(100),
	`provinceTh` varchar(100),
	`postalCodeTh` varchar(10),
	`phone` varchar(20),
	`email` varchar(320),
	`emergencyContact` varchar(255),
	`emergencyPhone` varchar(20),
	`employerId` int,
	`employerName` varchar(500),
	`position` varchar(255),
	`salary` int,
	`workStartDate` date,
	`workLocation` text,
	`jobDescription` text,
	`educationLevel` varchar(100),
	`educationDetails` varchar(500),
	`bloodType` varchar(10),
	`allergies` text,
	`medicalConditions` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `workers_id` PRIMARY KEY(`id`)
);
